# Generated by Django 4.1.6 on 2023-02-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('sanasi', models.DateField()),
                ('batafsil', models.CharField(max_length=500)),
                ('holat', models.CharField(max_length=100)),
            ],
        ),
    ]
